apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-4i4h
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-4i4h
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-4i4h
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-4i4h
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-4i4h
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tllu-tenant/status-quarkus-io/statusquarkusio-4i4h@sha256:4e164d8ec50019c9da7bf85e176013fb9952bb045548c6fa26992fcf7298d469
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
